import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { InventoryItem, StockAlert, StockAdjustment, Batch } from '../interfaces/inventory.interface';

@Injectable({
  providedIn: 'root'
})
export class InventoryMockService {

  private mockInventoryItems: InventoryItem[] = [
    {
      id: "INV-001",
      medicineId: "MED-1001",
      medicineName: "Paracetamol 500mg",
      presentation: "Tabletas",
      category: "Analgésicos",
      currentStock: 1250,
      minStock: 500,
      maxStock: 3000,
      reorderPoint: 750,
      unitCost: 0.15,
      totalValue: 187.5,
      location: "A-01-03",
      supplier: "Farmacéutica Nacional S.A.",
      lastRestockDate: "2024-09-15",
      lastMovementDate: "2024-09-28",
      status: "adequate",
      activeSubstance: "Paracetamol",
      averageConsumption: 150,
      daysOfStock: 8.3,
      batches: 3,
      nearestExpiry: "2025-03-15"
    },
    {
      id: "INV-002",
      medicineId: "MED-1002",
      medicineName: "Amoxicilina 500mg",
      presentation: "Cápsulas",
      category: "Antibióticos",
      currentStock: 320,
      minStock: 400,
      maxStock: 2000,
      reorderPoint: 600,
      unitCost: 0.45,
      totalValue: 144,
      location: "A-02-01",
      supplier: "Laboratorios Andinos",
      lastRestockDate: "2024-09-10",
      lastMovementDate: "2024-09-30",
      status: "low",
      activeSubstance: "Amoxicilina",
      averageConsumption: 80,
      daysOfStock: 4,
      batches: 2,
      nearestExpiry: "2025-06-20"
    },
    {
      id: "INV-003",
      medicineId: "MED-1003",
      medicineName: "Omeprazol 20mg",
      presentation: "Cápsulas",
      category: "Antiulcerosos",
      currentStock: 0,
      minStock: 300,
      maxStock: 1500,
      reorderPoint: 450,
      unitCost: 0.25,
      totalValue: 0,
      location: "A-03-02",
      supplier: "Distribuidora MedPharma",
      lastRestockDate: "2024-08-20",
      lastMovementDate: "2024-09-29",
      status: "out",
      activeSubstance: "Omeprazol",
      averageConsumption: 60,
      daysOfStock: 0,
      batches: 0,
      nearestExpiry: "-"
    },
    {
      id: "INV-004",
      medicineId: "MED-1004",
      medicineName: "Ibuprofeno 400mg",
      presentation: "Tabletas",
      category: "Antiinflamatorios",
      currentStock: 2800,
      minStock: 600,
      maxStock: 3500,
      reorderPoint: 900,
      unitCost: 0.18,
      totalValue: 504,
      location: "A-01-05",
      supplier: "Farmacéutica Nacional S.A.",
      lastRestockDate: "2024-09-25",
      lastMovementDate: "2024-09-30",
      status: "adequate",
      activeSubstance: "Ibuprofeno",
      averageConsumption: 120,
      daysOfStock: 23.3,
      batches: 4,
      nearestExpiry: "2025-08-10"
    },
    {
      id: "INV-005",
      medicineId: "MED-1005",
      medicineName: "Losartán 50mg",
      presentation: "Tabletas",
      category: "Antihipertensivos",
      currentStock: 580,
      minStock: 500,
      maxStock: 2500,
      reorderPoint: 750,
      unitCost: 0.32,
      totalValue: 185.6,
      location: "B-01-02",
      supplier: "Laboratorios Andinos",
      lastRestockDate: "2024-09-18",
      lastMovementDate: "2024-09-30",
      status: "adequate",
      activeSubstance: "Losartán potásico",
      averageConsumption: 90,
      daysOfStock: 6.4,
      batches: 2,
      nearestExpiry: "2025-04-25"
    },
    {
      id: "INV-006",
      medicineId: "MED-1006",
      medicineName: "Metformina 850mg",
      presentation: "Tabletas",
      category: "Antidiabéticos",
      currentStock: 250,
      minStock: 800,
      maxStock: 4000,
      reorderPoint: 1200,
      unitCost: 0.22,
      totalValue: 55,
      location: "B-02-01",
      supplier: "Distribuidora MedPharma",
      lastRestockDate: "2024-08-15",
      lastMovementDate: "2024-09-30",
      status: "critical",
      activeSubstance: "Metformina HCl",
      averageConsumption: 180,
      daysOfStock: 1.4,
      batches: 1,
      nearestExpiry: "2024-12-30"
    },
    {
      id: "INV-007",
      medicineId: "MED-1007",
      medicineName: "Atorvastatina 20mg",
      presentation: "Tabletas",
      category: "Hipolipemiantes",
      currentStock: 1450,
      minStock: 400,
      maxStock: 2000,
      reorderPoint: 600,
      unitCost: 0.38,
      totalValue: 551,
      location: "B-01-04",
      supplier: "Laboratorios Andinos",
      lastRestockDate: "2024-09-22",
      lastMovementDate: "2024-09-29",
      status: "adequate",
      activeSubstance: "Atorvastatina cálcica",
      averageConsumption: 70,
      daysOfStock: 20.7,
      batches: 3,
      nearestExpiry: "2025-07-18"
    },
    {
      id: "INV-008",
      medicineId: "MED-1008",
      medicineName: "Levotiroxina 100mcg",
      presentation: "Tabletas",
      category: "Hormonas tiroideas",
      currentStock: 3200,
      minStock: 300,
      maxStock: 3500,
      reorderPoint: 450,
      unitCost: 0.28,
      totalValue: 896,
      location: "C-01-01",
      supplier: "Farmacéutica Nacional S.A.",
      lastRestockDate: "2024-09-20",
      lastMovementDate: "2024-09-30",
      status: "overstocked",
      activeSubstance: "Levotiroxina sódica",
      averageConsumption: 50,
      daysOfStock: 64,
      batches: 5,
      nearestExpiry: "2025-11-05"
    }
  ];

  private mockStockAlerts: StockAlert[] = [
    {
      id: "ALERT-001",
      medicineId: "MED-1003",
      medicineName: "Omeprazol 20mg",
      presentation: "Cápsulas",
      currentStock: 0,
      minStock: 300,
      status: "out",
      priority: "critical",
      daysWithoutStock: 2,
      affectedPrescriptions: 8,
      estimatedDemand: 60,
      suggestedOrder: 900,
      lastRestockDate: "2024-08-20",
      supplier: "Distribuidora MedPharma",
      location: "A-03-02",
      category: "Antiulcerosos"
    },
    {
      id: "ALERT-002",
      medicineId: "MED-1006",
      medicineName: "Metformina 850mg",
      presentation: "Tabletas",
      currentStock: 250,
      minStock: 800,
      status: "critical",
      priority: "high",
      daysWithoutStock: 0,
      affectedPrescriptions: 0,
      estimatedDemand: 180,
      suggestedOrder: 2000,
      lastRestockDate: "2024-08-15",
      supplier: "Distribuidora MedPharma",
      location: "B-02-01",
      category: "Antidiabéticos"
    },
    {
      id: "ALERT-003",
      medicineId: "MED-1002",
      medicineName: "Amoxicilina 500mg",
      presentation: "Cápsulas",
      currentStock: 320,
      minStock: 400,
      status: "low",
      priority: "medium",
      daysWithoutStock: 0,
      affectedPrescriptions: 0,
      estimatedDemand: 80,
      suggestedOrder: 1000,
      lastRestockDate: "2024-09-10",
      supplier: "Laboratorios Andinos",
      location: "A-02-01",
      category: "Antibióticos"
    }
  ];

  private mockStockAdjustments: StockAdjustment[] = [
    {
      id: "ADJ-001",
      date: "2024-09-30",
      time: "14:30",
      type: "entry",
      medicineId: "MED-1001",
      medicineName: "Paracetamol 500mg",
      presentation: "Tabletas",
      quantity: 500,
      reason: "Compra regular",
      previousStock: 750,
      newStock: 1250,
      unitCost: 0.15,
      totalValue: 75,
      responsible: "Ana García",
      documentNumber: "FC-2024-0589",
      supplier: "Farmacéutica Nacional S.A.",
      batch: "LOT-2024-089",
      expiryDate: "2025-03-15",
      notes: "Entrega completa según orden de compra OC-589",
      status: "approved"
    },
    {
      id: "ADJ-002",
      date: "2024-09-29",
      time: "16:45",
      type: "exit",
      medicineId: "MED-1003",
      medicineName: "Omeprazol 20mg",
      presentation: "Cápsulas",
      quantity: 150,
      reason: "Dispensación farmacia",
      previousStock: 150,
      newStock: 0,
      unitCost: 0.25,
      totalValue: 37.5,
      responsible: "Carlos Méndez",
      documentNumber: "DISP-2024-1234",
      supplier: "-",
      batch: "LOT-2023-456",
      expiryDate: "2025-06-20",
      notes: "Stock agotado - generar orden de compra urgente",
      status: "approved"
    },
    {
      id: "ADJ-003",
      date: "2024-09-28",
      time: "10:15",
      type: "adjustment",
      medicineId: "MED-1004",
      medicineName: "Ibuprofeno 400mg",
      presentation: "Tabletas",
      quantity: -50,
      reason: "Vencimiento",
      previousStock: 2850,
      newStock: 2800,
      unitCost: 0.18,
      totalValue: -9,
      responsible: "Ana García",
      documentNumber: "AJ-2024-045",
      supplier: "-",
      batch: "LOT-2022-789",
      expiryDate: "2024-09-25",
      notes: "Producto vencido - destrucción según protocolo sanitario",
      status: "approved"
    },
    {
      id: "ADJ-004",
      date: "2024-09-27",
      time: "11:00",
      type: "entry",
      medicineId: "MED-1007",
      medicineName: "Atorvastatina 20mg",
      presentation: "Tabletas",
      quantity: 1000,
      reason: "Compra urgente",
      previousStock: 450,
      newStock: 1450,
      unitCost: 0.38,
      totalValue: 380,
      responsible: "Luis Fernández",
      documentNumber: "FC-2024-0601",
      supplier: "Laboratorios Andinos",
      batch: "LOT-2024-112",
      expiryDate: "2025-07-18",
      notes: "Orden urgente por stock bajo",
      status: "approved"
    },
    {
      id: "ADJ-005",
      date: "2024-09-26",
      time: "09:30",
      type: "adjustment",
      medicineId: "MED-1002",
      medicineName: "Amoxicilina 500mg",
      presentation: "Cápsulas",
      quantity: -30,
      reason: "Devolución proveedor",
      previousStock: 350,
      newStock: 320,
      unitCost: 0.45,
      totalValue: -13.5,
      responsible: "Ana García",
      documentNumber: "DEV-2024-023",
      supplier: "Laboratorios Andinos",
      batch: "LOT-2024-067",
      expiryDate: "2025-06-20",
      notes: "Producto con defecto de fabricación - reembolso gestionado",
      status: "approved"
    }
  ];

  private mockBatches: Batch[] = [
    {
      id: "BATCH-001",
      batchNumber: "LOT-2024-089",
      medicineId: "MED-1001",
      medicineName: "Paracetamol 500mg",
      presentation: "Tabletas",
      supplier: "Farmacéutica Nacional S.A.",
      manufacturingDate: "2024-03-15",
      expiryDate: "2025-03-15",
      quantity: 500,
      remainingQuantity: 450,
      location: "A-01-03",
      status: "active",
      daysToExpiry: 166,
      unitCost: 0.15,
      totalValue: 67.5,
      entryDate: "2024-09-30",
      documentNumber: "FC-2024-0589"
    },
    {
      id: "BATCH-002",
      batchNumber: "LOT-2023-456",
      medicineId: "MED-1002",
      medicineName: "Amoxicilina 500mg",
      presentation: "Cápsulas",
      supplier: "Laboratorios Andinos",
      manufacturingDate: "2023-12-20",
      expiryDate: "2025-06-20",
      quantity: 500,
      remainingQuantity: 320,
      location: "A-02-01",
      status: "active",
      daysToExpiry: 263,
      unitCost: 0.45,
      totalValue: 144,
      entryDate: "2024-09-10",
      documentNumber: "FC-2024-0512"
    },
    {
      id: "BATCH-003",
      batchNumber: "LOT-2024-034",
      medicineId: "MED-1005",
      medicineName: "Losartán 50mg",
      presentation: "Tabletas",
      supplier: "Laboratorios Andinos",
      manufacturingDate: "2024-01-25",
      expiryDate: "2025-04-25",
      quantity: 600,
      remainingQuantity: 580,
      location: "B-01-02",
      status: "active",
      daysToExpiry: 207,
      unitCost: 0.32,
      totalValue: 185.6,
      entryDate: "2024-09-18",
      documentNumber: "FC-2024-0575"
    },
    {
      id: "BATCH-004",
      batchNumber: "LOT-2022-789",
      medicineId: "MED-1004",
      medicineName: "Ibuprofeno 400mg",
      presentation: "Tabletas",
      supplier: "Farmacéutica Nacional S.A.",
      manufacturingDate: "2022-09-25",
      expiryDate: "2024-09-25",
      quantity: 200,
      remainingQuantity: 0,
      location: "A-01-05",
      status: "expired",
      daysToExpiry: -6,
      unitCost: 0.18,
      totalValue: 0,
      entryDate: "2023-02-10",
      documentNumber: "FC-2023-0145"
    },
    {
      id: "BATCH-005",
      batchNumber: "LOT-2024-156",
      medicineId: "MED-1006",
      medicineName: "Metformina 850mg",
      presentation: "Tabletas",
      supplier: "Distribuidora MedPharma",
      manufacturingDate: "2023-12-30",
      expiryDate: "2024-12-30",
      quantity: 500,
      remainingQuantity: 250,
      location: "B-02-01",
      status: "near_expiry",
      daysToExpiry: 91,
      unitCost: 0.22,
      totalValue: 55,
      entryDate: "2024-08-15",
      documentNumber: "FC-2024-0456"
    },
    {
      id: "BATCH-006",
      batchNumber: "LOT-2024-112",
      medicineId: "MED-1007",
      medicineName: "Atorvastatina 20mg",
      presentation: "Tabletas",
      supplier: "Laboratorios Andinos",
      manufacturingDate: "2024-01-18",
      expiryDate: "2025-07-18",
      quantity: 1000,
      remainingQuantity: 1000,
      location: "B-01-04",
      status: "active",
      daysToExpiry: 291,
      unitCost: 0.38,
      totalValue: 380,
      entryDate: "2024-09-27",
      documentNumber: "FC-2024-0601"
    },
    {
      id: "BATCH-007",
      batchNumber: "LOT-2023-998",
      medicineId: "MED-1008",
      medicineName: "Levotiroxina 100mcg",
      presentation: "Tabletas",
      supplier: "Farmacéutica Nacional S.A.",
      manufacturingDate: "2023-11-05",
      expiryDate: "2025-11-05",
      quantity: 800,
      remainingQuantity: 750,
      location: "C-01-01",
      status: "active",
      daysToExpiry: 401,
      unitCost: 0.28,
      totalValue: 210,
      entryDate: "2024-09-20",
      documentNumber: "FC-2024-0580"
    },
    {
      id: "BATCH-008",
      batchNumber: "LOT-2024-201",
      medicineId: "MED-1004",
      medicineName: "Ibuprofeno 400mg",
      presentation: "Tabletas",
      supplier: "Farmacéutica Nacional S.A.",
      manufacturingDate: "2024-02-10",
      expiryDate: "2025-08-10",
      quantity: 1000,
      remainingQuantity: 850,
      location: "A-01-05",
      status: "active",
      daysToExpiry: 314,
      unitCost: 0.18,
      totalValue: 153,
      entryDate: "2024-09-25",
      documentNumber: "FC-2024-0595"
    }
  ];

  getInventoryItems(): Observable<InventoryItem[]> {
    return of(this.mockInventoryItems);
  }

  getStockAlerts(): Observable<StockAlert[]> {
    return of(this.mockStockAlerts);
  }

  getStockAdjustments(): Observable<StockAdjustment[]> {
    return of(this.mockStockAdjustments);
  }

  getBatches(): Observable<Batch[]> {
    return of(this.mockBatches);
  }

  getInventoryItemById(id: string): Observable<InventoryItem | undefined> {
    const item = this.mockInventoryItems.find(item => item.id === id);
    return of(item);
  }

  getStockAlertById(id: string): Observable<StockAlert | undefined> {
    const alert = this.mockStockAlerts.find(alert => alert.id === id);
    return of(alert);
  }

  getStockAdjustmentById(id: string): Observable<StockAdjustment | undefined> {
    const adjustment = this.mockStockAdjustments.find(adj => adj.id === id);
    return of(adjustment);
  }

  getBatchById(id: string): Observable<Batch | undefined> {
    const batch = this.mockBatches.find(batch => batch.id === id);
    return of(batch);
  }
}