-- =====================================================
-- Script: 03-specialties-routes-data.sql
-- Description: Seed data for SPECIALTIES and ADMINISTRATION_ROUTES tables
-- Uses SNOMED CT codes (WHO standard) for medical specialties
-- Compatible with HL7 FHIR R4, OMS/WHO standards
-- Follows DATABASE-SCHEMA-REFERENCE.md structure
-- Uses MERGE to avoid duplicates and integrity violations
-- =====================================================

-- Configure session for UTF-8
ALTER SESSION SET NLS_LANGUAGE='SPANISH';
ALTER SESSION SET NLS_TERRITORY='COSTA RICA';

SET DEFINE OFF;
SET SERVEROUTPUT ON;

PROMPT ========================================
PROMPT Inserting SPECIALTIES with SNOMED CT codes
PROMPT ========================================

-- Note: Not deleting routes as they may have dependencies (medications)

PROMPT Merging 25 medical specialties with SNOMED CT codes...

-- Medical Specialties with SNOMED CT codes (http://snomed.info/sct)
-- Using MERGE to avoid duplicates

MERGE INTO SPECIALTIES dst
USING (SELECT '394814009' as SPECIALTY_CODE, 'Medicina General' as SPECIALTY_NAME, 'Atención médica general y preventiva' as DESCRIPTION FROM DUAL) src
ON (dst.SPECIALTY_CODE = src.SPECIALTY_CODE)
WHEN NOT MATCHED THEN INSERT (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES (src.SPECIALTY_CODE, src.SPECIALTY_NAME, src.DESCRIPTION);

MERGE INTO SPECIALTIES dst
USING (SELECT '394579002' as SPECIALTY_CODE, 'Cardiología' as SPECIALTY_NAME, 'Especialidad médica que se ocupa de las enfermedades del corazón y del aparato circulatorio' as DESCRIPTION FROM DUAL) src
ON (dst.SPECIALTY_CODE = src.SPECIALTY_CODE)
WHEN NOT MATCHED THEN INSERT (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES (src.SPECIALTY_CODE, src.SPECIALTY_NAME, src.DESCRIPTION);

MERGE INTO SPECIALTIES dst
USING (SELECT '394582007' as SPECIALTY_CODE, 'Dermatología' as SPECIALTY_NAME, 'Especialidad médica que se ocupa de las enfermedades de la piel' as DESCRIPTION FROM DUAL) src
ON (dst.SPECIALTY_CODE = src.SPECIALTY_CODE)
WHEN NOT MATCHED THEN INSERT (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES (src.SPECIALTY_CODE, src.SPECIALTY_NAME, src.DESCRIPTION);

MERGE INTO SPECIALTIES dst
USING (SELECT '394583002' as SPECIALTY_CODE, 'Endocrinología' as SPECIALTY_NAME, 'Especialidad médica que estudia las hormonas y las glándulas que las producen' as DESCRIPTION FROM DUAL) src
ON (dst.SPECIALTY_CODE = src.SPECIALTY_CODE)
WHEN NOT MATCHED THEN INSERT (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES (src.SPECIALTY_CODE, src.SPECIALTY_NAME, src.DESCRIPTION);

MERGE INTO SPECIALTIES dst
USING (SELECT '394584008' as SPECIALTY_CODE, 'Gastroenterología' as SPECIALTY_NAME, 'Especialidad médica que se ocupa del aparato digestivo y sus enfermedades' as DESCRIPTION FROM DUAL) src
ON (dst.SPECIALTY_CODE = src.SPECIALTY_CODE)
WHEN NOT MATCHED THEN INSERT (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES (src.SPECIALTY_CODE, src.SPECIALTY_NAME, src.DESCRIPTION);


MERGE INTO SPECIALTIES dst
USING (SELECT '394586005' as SPECIALTY_CODE, 'Ginecología y Obstetricia' as SPECIALTY_NAME, 'Especialidad médica que trata las enfermedades del sistema reproductor femenino y el embarazo' as DESCRIPTION FROM DUAL) src
ON (dst.SPECIALTY_CODE = src.SPECIALTY_CODE)
WHEN NOT MATCHED THEN INSERT (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES (src.SPECIALTY_CODE, src.SPECIALTY_NAME, src.DESCRIPTION);

MERGE INTO SPECIALTIES dst
USING (SELECT '394803003' as SPECIALTY_CODE, 'Hematología' as SPECIALTY_NAME, 'Especialidad médica que estudia la sangre y sus enfermedades' as DESCRIPTION FROM DUAL) src
ON (dst.SPECIALTY_CODE = src.SPECIALTY_CODE)
WHEN NOT MATCHED THEN INSERT (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES (src.SPECIALTY_CODE, src.SPECIALTY_NAME, src.DESCRIPTION);

MERGE INTO SPECIALTIES dst
USING (SELECT '394807002' as SPECIALTY_CODE, 'Infectología' as SPECIALTY_NAME, 'Especialidad médica que se dedica al estudio, diagnóstico y tratamiento de las enfermedades infecciosas' as DESCRIPTION FROM DUAL) src
ON (dst.SPECIALTY_CODE = src.SPECIALTY_CODE)
WHEN NOT MATCHED THEN INSERT (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES (src.SPECIALTY_CODE, src.SPECIALTY_NAME, src.DESCRIPTION);

MERGE INTO SPECIALTIES dst
USING (SELECT '419192003' as SPECIALTY_CODE, 'Medicina Interna' as SPECIALTY_NAME, 'Especialidad médica que se dedica a la atención integral del adulto' as DESCRIPTION FROM DUAL) src
ON (dst.SPECIALTY_CODE = src.SPECIALTY_CODE)
WHEN NOT MATCHED THEN INSERT (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES (src.SPECIALTY_CODE, src.SPECIALTY_NAME, src.DESCRIPTION);

MERGE INTO SPECIALTIES dst
USING (SELECT '394589003' as SPECIALTY_CODE, 'Nefrología' as SPECIALTY_NAME, 'Especialidad médica que estudia las enfermedades del riñón' as DESCRIPTION FROM DUAL) src
ON (dst.SPECIALTY_CODE = src.SPECIALTY_CODE)
WHEN NOT MATCHED THEN INSERT (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES (src.SPECIALTY_CODE, src.SPECIALTY_NAME, src.DESCRIPTION);

MERGE INTO SPECIALTIES dst
USING (SELECT '394810000' as SPECIALTY_CODE, 'Neumología' as SPECIALTY_NAME, 'Especialidad médica que se ocupa de las enfermedades del aparato respiratorio' as DESCRIPTION FROM DUAL) src
ON (dst.SPECIALTY_CODE = src.SPECIALTY_CODE)
WHEN NOT MATCHED THEN INSERT (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES (src.SPECIALTY_CODE, src.SPECIALTY_NAME, src.DESCRIPTION);

MERGE INTO SPECIALTIES dst
USING (SELECT '394591006' as SPECIALTY_CODE, 'Neurología' as SPECIALTY_NAME, 'Especialidad médica que trata los trastornos del sistema nervioso' as DESCRIPTION FROM DUAL) src
ON (dst.SPECIALTY_CODE = src.SPECIALTY_CODE)
WHEN NOT MATCHED THEN INSERT (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES (src.SPECIALTY_CODE, src.SPECIALTY_NAME, src.DESCRIPTION);

MERGE INTO SPECIALTIES dst
USING (SELECT '394594003' as SPECIALTY_CODE, 'Oftalmología' as SPECIALTY_NAME, 'Especialidad médica que estudia las enfermedades de los ojos' as DESCRIPTION FROM DUAL) src
ON (dst.SPECIALTY_CODE = src.SPECIALTY_CODE)
WHEN NOT MATCHED THEN INSERT (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES (src.SPECIALTY_CODE, src.SPECIALTY_NAME, src.DESCRIPTION);

MERGE INTO SPECIALTIES dst
USING (SELECT '394592004' as SPECIALTY_CODE, 'Oncología' as SPECIALTY_NAME, 'Especialidad médica que estudia y trata el cáncer' as DESCRIPTION FROM DUAL) src
ON (dst.SPECIALTY_CODE = src.SPECIALTY_CODE)
WHEN NOT MATCHED THEN INSERT (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES (src.SPECIALTY_CODE, src.SPECIALTY_NAME, src.DESCRIPTION);

MERGE INTO SPECIALTIES dst
USING (SELECT '394801008' as SPECIALTY_CODE, 'Ortopedia y Traumatología' as SPECIALTY_NAME, 'Especialidad médica dedicada al diagnóstico y tratamiento de lesiones del sistema musculoesquelético' as DESCRIPTION FROM DUAL) src
ON (dst.SPECIALTY_CODE = src.SPECIALTY_CODE)
WHEN NOT MATCHED THEN INSERT (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES (src.SPECIALTY_CODE, src.SPECIALTY_NAME, src.DESCRIPTION);

MERGE INTO SPECIALTIES dst
USING (SELECT '418960008' as SPECIALTY_CODE, 'Otorrinolaringología' as SPECIALTY_NAME, 'Especialidad médica que trata las enfermedades del oído, nariz y garganta' as DESCRIPTION FROM DUAL) src
ON (dst.SPECIALTY_CODE = src.SPECIALTY_CODE)
WHEN NOT MATCHED THEN INSERT (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES (src.SPECIALTY_CODE, src.SPECIALTY_NAME, src.DESCRIPTION);

MERGE INTO SPECIALTIES dst
USING (SELECT '394537008' as SPECIALTY_CODE, 'Pediatría' as SPECIALTY_NAME, 'Especialidad médica que estudia al niño y sus enfermedades' as DESCRIPTION FROM DUAL) src
ON (dst.SPECIALTY_CODE = src.SPECIALTY_CODE)
WHEN NOT MATCHED THEN INSERT (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES (src.SPECIALTY_CODE, src.SPECIALTY_NAME, src.DESCRIPTION);

MERGE INTO SPECIALTIES dst
USING (SELECT '394587001' as SPECIALTY_CODE, 'Psiquiatría' as SPECIALTY_NAME, 'Especialidad médica dedicada al estudio y tratamiento de los trastornos mentales' as DESCRIPTION FROM DUAL) src
ON (dst.SPECIALTY_CODE = src.SPECIALTY_CODE)
WHEN NOT MATCHED THEN INSERT (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES (src.SPECIALTY_CODE, src.SPECIALTY_NAME, src.DESCRIPTION);

MERGE INTO SPECIALTIES dst
USING (SELECT '394810007' as SPECIALTY_CODE, 'Reumatología' as SPECIALTY_NAME, 'Especialidad médica que se ocupa de las enfermedades del aparato locomotor y del tejido conectivo' as DESCRIPTION FROM DUAL) src
ON (dst.SPECIALTY_CODE = src.SPECIALTY_CODE)
WHEN NOT MATCHED THEN INSERT (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES (src.SPECIALTY_CODE, src.SPECIALTY_NAME, src.DESCRIPTION);

MERGE INTO SPECIALTIES dst
USING (SELECT '394612005' as SPECIALTY_CODE, 'Urología' as SPECIALTY_NAME, 'Especialidad médica que se ocupa del estudio del aparato urinario y reproductor masculino' as DESCRIPTION FROM DUAL) src
ON (dst.SPECIALTY_CODE = src.SPECIALTY_CODE)
WHEN NOT MATCHED THEN INSERT (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES (src.SPECIALTY_CODE, src.SPECIALTY_NAME, src.DESCRIPTION);

MERGE INTO SPECIALTIES dst
USING (SELECT '394609007' as SPECIALTY_CODE, 'Cirugía General' as SPECIALTY_NAME, 'Especialidad médica que se ocupa de procedimientos quirúrgicos del aparato digestivo y otros órganos' as DESCRIPTION FROM DUAL) src
ON (dst.SPECIALTY_CODE = src.SPECIALTY_CODE)
WHEN NOT MATCHED THEN INSERT (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES (src.SPECIALTY_CODE, src.SPECIALTY_NAME, src.DESCRIPTION);

MERGE INTO SPECIALTIES dst
USING (SELECT '394577000' as SPECIALTY_CODE, 'Anestesiología' as SPECIALTY_NAME, 'Especialidad médica dedicada a la anestesia y el manejo del dolor' as DESCRIPTION FROM DUAL) src
ON (dst.SPECIALTY_CODE = src.SPECIALTY_CODE)
WHEN NOT MATCHED THEN INSERT (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES (src.SPECIALTY_CODE, src.SPECIALTY_NAME, src.DESCRIPTION);

MERGE INTO SPECIALTIES dst
USING (SELECT '419815003' as SPECIALTY_CODE, 'Radiología' as SPECIALTY_NAME, 'Especialidad médica que utiliza imágenes para diagnosticar y tratar enfermedades' as DESCRIPTION FROM DUAL) src
ON (dst.SPECIALTY_CODE = src.SPECIALTY_CODE)
WHEN NOT MATCHED THEN INSERT (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES (src.SPECIALTY_CODE, src.SPECIALTY_NAME, src.DESCRIPTION);

MERGE INTO SPECIALTIES dst
USING (SELECT '773568002' as SPECIALTY_CODE, 'Medicina de Emergencia' as SPECIALTY_NAME, 'Especialidad médica que se ocupa de la atención de urgencias y emergencias' as DESCRIPTION FROM DUAL) src
ON (dst.SPECIALTY_CODE = src.SPECIALTY_CODE)
WHEN NOT MATCHED THEN INSERT (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES (src.SPECIALTY_CODE, src.SPECIALTY_NAME, src.DESCRIPTION);

MERGE INTO SPECIALTIES dst
USING (SELECT '394811001' as SPECIALTY_CODE, 'Geriatría' as SPECIALTY_NAME, 'Especialidad médica que se ocupa de la salud de las personas mayores' as DESCRIPTION FROM DUAL) src
ON (dst.SPECIALTY_CODE = src.SPECIALTY_CODE)
WHEN NOT MATCHED THEN INSERT (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES (src.SPECIALTY_CODE, src.SPECIALTY_NAME, src.DESCRIPTION);

COMMIT;


PROMPT Merging 20 administration routes (avoiding duplicates)...

-- Administration Routes for Medications (with codes) - Using MERGE
MERGE INTO ADMINISTRATION_ROUTES dst
USING (SELECT 'ORAL' as ROUTE_CODE, 'Oral' as ROUTE_NAME, 'Administración por vía oral (boca)' as DESCRIPTION FROM DUAL) src
ON (dst.ROUTE_CODE = src.ROUTE_CODE)
WHEN NOT MATCHED THEN INSERT (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES (src.ROUTE_CODE, src.ROUTE_NAME, src.DESCRIPTION);

MERGE INTO ADMINISTRATION_ROUTES dst
USING (SELECT 'SUBL' as ROUTE_CODE, 'Sublingual' as ROUTE_NAME, 'Administración debajo de la lengua' as DESCRIPTION FROM DUAL) src
ON (dst.ROUTE_CODE = src.ROUTE_CODE)
WHEN NOT MATCHED THEN INSERT (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES (src.ROUTE_CODE, src.ROUTE_NAME, src.DESCRIPTION);

MERGE INTO ADMINISTRATION_ROUTES dst
USING (SELECT 'IV' as ROUTE_CODE, 'Intravenosa' as ROUTE_NAME, 'Administración directa en vena' as DESCRIPTION FROM DUAL) src
ON (dst.ROUTE_CODE = src.ROUTE_CODE)
WHEN NOT MATCHED THEN INSERT (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES (src.ROUTE_CODE, src.ROUTE_NAME, src.DESCRIPTION);

MERGE INTO ADMINISTRATION_ROUTES dst
USING (SELECT 'IM' as ROUTE_CODE, 'Intramuscular' as ROUTE_NAME, 'Administración en músculo' as DESCRIPTION FROM DUAL) src
ON (dst.ROUTE_CODE = src.ROUTE_CODE)
WHEN NOT MATCHED THEN INSERT (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES (src.ROUTE_CODE, src.ROUTE_NAME, src.DESCRIPTION);

MERGE INTO ADMINISTRATION_ROUTES dst
USING (SELECT 'SC' as ROUTE_CODE, 'Subcutánea' as ROUTE_NAME, 'Administración bajo la piel' as DESCRIPTION FROM DUAL) src
ON (dst.ROUTE_CODE = src.ROUTE_CODE)
WHEN NOT MATCHED THEN INSERT (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES (src.ROUTE_CODE, src.ROUTE_NAME, src.DESCRIPTION);

MERGE INTO ADMINISTRATION_ROUTES dst
USING (SELECT 'TOP' as ROUTE_CODE, 'Tópica' as ROUTE_NAME, 'Aplicación sobre la piel' as DESCRIPTION FROM DUAL) src
ON (dst.ROUTE_CODE = src.ROUTE_CODE)
WHEN NOT MATCHED THEN INSERT (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES (src.ROUTE_CODE, src.ROUTE_NAME, src.DESCRIPTION);

MERGE INTO ADMINISTRATION_ROUTES dst
USING (SELECT 'TRANS' as ROUTE_CODE, 'Transdérmica' as ROUTE_NAME, 'Absorción a través de la piel (parches)' as DESCRIPTION FROM DUAL) src
ON (dst.ROUTE_CODE = src.ROUTE_CODE)
WHEN NOT MATCHED THEN INSERT (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES (src.ROUTE_CODE, src.ROUTE_NAME, src.DESCRIPTION);

MERGE INTO ADMINISTRATION_ROUTES dst
USING (SELECT 'INHAL' as ROUTE_CODE, 'Inhalatoria' as ROUTE_NAME, 'Administración por inhalación' as DESCRIPTION FROM DUAL) src
ON (dst.ROUTE_CODE = src.ROUTE_CODE)
WHEN NOT MATCHED THEN INSERT (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES (src.ROUTE_CODE, src.ROUTE_NAME, src.DESCRIPTION);

MERGE INTO ADMINISTRATION_ROUTES dst
USING (SELECT 'NASAL' as ROUTE_CODE, 'Nasal' as ROUTE_NAME, 'Administración por vía nasal' as DESCRIPTION FROM DUAL) src
ON (dst.ROUTE_CODE = src.ROUTE_CODE)
WHEN NOT MATCHED THEN INSERT (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES (src.ROUTE_CODE, src.ROUTE_NAME, src.DESCRIPTION);

MERGE INTO ADMINISTRATION_ROUTES dst
USING (SELECT 'OFTAL' as ROUTE_CODE, 'Oftálmica' as ROUTE_NAME, 'Aplicación en los ojos' as DESCRIPTION FROM DUAL) src
ON (dst.ROUTE_CODE = src.ROUTE_CODE)
WHEN NOT MATCHED THEN INSERT (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES (src.ROUTE_CODE, src.ROUTE_NAME, src.DESCRIPTION);

MERGE INTO ADMINISTRATION_ROUTES dst
USING (SELECT 'OTIC' as ROUTE_CODE, 'Ótica' as ROUTE_NAME, 'Aplicación en los oídos' as DESCRIPTION FROM DUAL) src
ON (dst.ROUTE_CODE = src.ROUTE_CODE)
WHEN NOT MATCHED THEN INSERT (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES (src.ROUTE_CODE, src.ROUTE_NAME, src.DESCRIPTION);

MERGE INTO ADMINISTRATION_ROUTES dst
USING (SELECT 'RECT' as ROUTE_CODE, 'Rectal' as ROUTE_NAME, 'Administración por vía rectal' as DESCRIPTION FROM DUAL) src
ON (dst.ROUTE_CODE = src.ROUTE_CODE)
WHEN NOT MATCHED THEN INSERT (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES (src.ROUTE_CODE, src.ROUTE_NAME, src.DESCRIPTION);

MERGE INTO ADMINISTRATION_ROUTES dst
USING (SELECT 'VAG' as ROUTE_CODE, 'Vaginal' as ROUTE_NAME, 'Administración por vía vaginal' as DESCRIPTION FROM DUAL) src
ON (dst.ROUTE_CODE = src.ROUTE_CODE)
WHEN NOT MATCHED THEN INSERT (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES (src.ROUTE_CODE, src.ROUTE_NAME, src.DESCRIPTION);

MERGE INTO ADMINISTRATION_ROUTES dst
USING (SELECT 'ID' as ROUTE_CODE, 'Intradérmica' as ROUTE_NAME, 'Administración en la dermis' as DESCRIPTION FROM DUAL) src
ON (dst.ROUTE_CODE = src.ROUTE_CODE)
WHEN NOT MATCHED THEN INSERT (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES (src.ROUTE_CODE, src.ROUTE_NAME, src.DESCRIPTION);

MERGE INTO ADMINISTRATION_ROUTES dst
USING (SELECT 'IP' as ROUTE_CODE, 'Intraperitoneal' as ROUTE_NAME, 'Administración en la cavidad peritoneal' as DESCRIPTION FROM DUAL) src
ON (dst.ROUTE_CODE = src.ROUTE_CODE)
WHEN NOT MATCHED THEN INSERT (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES (src.ROUTE_CODE, src.ROUTE_NAME, src.DESCRIPTION);

MERGE INTO ADMINISTRATION_ROUTES dst
USING (SELECT 'IT' as ROUTE_CODE, 'Intratecal' as ROUTE_NAME, 'Administración en el espacio subaracnoideo' as DESCRIPTION FROM DUAL) src
ON (dst.ROUTE_CODE = src.ROUTE_CODE)
WHEN NOT MATCHED THEN INSERT (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES (src.ROUTE_CODE, src.ROUTE_NAME, src.DESCRIPTION);

MERGE INTO ADMINISTRATION_ROUTES dst
USING (SELECT 'EPID' as ROUTE_CODE, 'Epidural' as ROUTE_NAME, 'Administración en el espacio epidural' as DESCRIPTION FROM DUAL) src
ON (dst.ROUTE_CODE = src.ROUTE_CODE)
WHEN NOT MATCHED THEN INSERT (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES (src.ROUTE_CODE, src.ROUTE_NAME, src.DESCRIPTION);

MERGE INTO ADMINISTRATION_ROUTES dst
USING (SELECT 'IA' as ROUTE_CODE, 'Intraarticular' as ROUTE_NAME, 'Administración dentro de una articulación' as DESCRIPTION FROM DUAL) src
ON (dst.ROUTE_CODE = src.ROUTE_CODE)
WHEN NOT MATCHED THEN INSERT (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES (src.ROUTE_CODE, src.ROUTE_NAME, src.DESCRIPTION);

MERGE INTO ADMINISTRATION_ROUTES dst
USING (SELECT 'BUCAL' as ROUTE_CODE, 'Bucal' as ROUTE_NAME, 'Administración entre la mejilla y la encía' as DESCRIPTION FROM DUAL) src
ON (dst.ROUTE_CODE = src.ROUTE_CODE)
WHEN NOT MATCHED THEN INSERT (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES (src.ROUTE_CODE, src.ROUTE_NAME, src.DESCRIPTION);

MERGE INTO ADMINISTRATION_ROUTES dst
USING (SELECT 'PARENT' as ROUTE_CODE, 'Parenteral' as ROUTE_NAME, 'Administración que evita el tracto gastrointestinal' as DESCRIPTION FROM DUAL) src
ON (dst.ROUTE_CODE = src.ROUTE_CODE)
WHEN NOT MATCHED THEN INSERT (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES (src.ROUTE_CODE, src.ROUTE_NAME, src.DESCRIPTION);

COMMIT;

PROMPT 
PROMPT ========================================
PROMPT SPECIALTIES and ROUTES Data Completed!
PROMPT ========================================
PROMPT Specialties: SNOMED CT codes (WHO standard)
PROMPT Routes: Standard HL7 FHIR codes
PROMPT Compatible with HL7 FHIR R4 and OMS standards
PROMPT ========================================

-- Verify data
SELECT COUNT(*) as TOTAL_SPECIALTIES FROM SPECIALTIES;
SELECT COUNT(*) as TOTAL_ROUTES FROM ADMINISTRATION_ROUTES;

SELECT 'Sample specialties with SNOMED CT codes:' as INFO FROM DUAL;
SELECT SPECIALTY_CODE, SPECIALTY_NAME
FROM SPECIALTIES
WHERE SPECIALTY_NAME LIKE '%ía%' OR SPECIALTY_NAME LIKE '%ó%'
FETCH FIRST 5 ROWS ONLY;

PROMPT ========================================

EXIT;
