-- =====================================================
-- Script: 06-medications-data.sql
-- Description: Seed data for MEDICATIONS table
-- Uses WHO ATC (Anatomical Therapeutic Chemical) codes
-- Compatible with HL7 FHIR R4, OMS/WHO standards
-- Contains 35 common medications with proper UTF-8 encoding
-- Follows DATABASE-SCHEMA-REFERENCE.md structure
-- =====================================================

-- Configure session for UTF-8
ALTER SESSION SET NLS_LANGUAGE='SPANISH';
ALTER SESSION SET NLS_TERRITORY='COSTA RICA';

SET DEFINE OFF;
SET SERVEROUTPUT ON;

PROMPT ========================================
PROMPT Inserting MEDICATIONS with WHO ATC codes
PROMPT ========================================

-- Clear existing data
DELETE FROM MEDICATIONS;

PROMPT Inserting medications with WHO ATC standard codes...

-- Get route IDs for reference
DECLARE
    v_oral_id RAW(16);
    v_subl_id RAW(16);
    v_iv_id RAW(16);
    v_im_id RAW(16);
    v_sc_id RAW(16);
    v_top_id RAW(16);
    v_inhal_id RAW(16);
    v_oftal_id RAW(16);
    v_count NUMBER := 0;
BEGIN
    -- Get route IDs
    SELECT ROUTE_ID INTO v_oral_id FROM ADMINISTRATION_ROUTES WHERE ROUTE_CODE = 'ORAL';
    SELECT ROUTE_ID INTO v_subl_id FROM ADMINISTRATION_ROUTES WHERE ROUTE_CODE = 'SUBL';
    SELECT ROUTE_ID INTO v_iv_id FROM ADMINISTRATION_ROUTES WHERE ROUTE_CODE = 'IV';
    SELECT ROUTE_ID INTO v_im_id FROM ADMINISTRATION_ROUTES WHERE ROUTE_CODE = 'IM';
    SELECT ROUTE_ID INTO v_sc_id FROM ADMINISTRATION_ROUTES WHERE ROUTE_CODE = 'SC';
    SELECT ROUTE_ID INTO v_top_id FROM ADMINISTRATION_ROUTES WHERE ROUTE_CODE = 'TOP';
    SELECT ROUTE_ID INTO v_inhal_id FROM ADMINISTRATION_ROUTES WHERE ROUTE_CODE = 'INHAL';
    SELECT ROUTE_ID INTO v_oftal_id FROM ADMINISTRATION_ROUTES WHERE ROUTE_CODE = 'OFTAL';
    
    -- N: SISTEMA NERVIOSO - Analgésicos y Antiinflamatorios
    
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('N02BE01', 'Tylenol', 'Paracetamol', 'Paracetamol', 'Tableta', '500mg', v_oral_id, 0, 1);
    
    -- M: SISTEMA MUSCULOESQUELÉTICO - Antiinflamatorios
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('M01AE01', 'Advil', 'Ibuprofeno', 'Ibuprofeno', 'Tableta', '400mg', v_oral_id, 0, 1);
    
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('M01AB05', 'Voltaren', 'Diclofenaco', 'Diclofenaco sódico', 'Tableta', '50mg', v_oral_id, 1, 1);
    
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('M01AE02', 'Aleve', 'Naproxeno', 'Naproxeno sódico', 'Tableta', '250mg', v_oral_id, 0, 1);
    
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('M01AB15', 'Toradol', 'Ketorolaco', 'Ketorolaco trometamina', 'Ampolla', '30mg/ml', v_im_id, 1, 1);
    
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('N02AX02', 'Tramal', 'Tramadol', 'Tramadol clorhidrato', 'Cápsula', '50mg', v_oral_id, 1, 1);
    
    -- J: ANTIINFECCIOSOS - Antibióticos
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('J01CA04', 'Amoxil', 'Amoxicilina', 'Amoxicilina trihidrato', 'Cápsula', '500mg', v_oral_id, 1, 1);
    
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('J01CR02', 'Augmentin', 'Amoxicilina + Ácido Clavulánico', 'Amoxicilina + Ácido Clavulánico', 'Tableta', '875mg/125mg', v_oral_id, 1, 1);
    
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('J01FA10', 'Zithromax', 'Azitromicina', 'Azitromicina dihidrato', 'Tableta', '500mg', v_oral_id, 1, 1);
    
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('J01MA02', 'Cipro', 'Ciprofloxacino', 'Ciprofloxacino clorhidrato', 'Tableta', '500mg', v_oral_id, 1, 1);
    
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('J01DB01', 'Keflex', 'Cefalexina', 'Cefalexina monohidrato', 'Cápsula', '500mg', v_oral_id, 1, 1);
    
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('J01DD04', 'Rocephin', 'Ceftriaxona', 'Ceftriaxona sódica', 'Ampolla', '1g', v_iv_id, 1, 1);
    
    -- C: SISTEMA CARDIOVASCULAR - Antihipertensivos
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('C09AA02', 'Vasotec', 'Enalapril', 'Enalapril maleato', 'Tableta', '10mg', v_oral_id, 1, 1);
    
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('C09CA01', 'Cozaar', 'Losartán', 'Losartán potásico', 'Tableta', '50mg', v_oral_id, 1, 1);
    
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('C08CA01', 'Norvasc', 'Amlodipino', 'Amlodipino besilato', 'Tableta', '5mg', v_oral_id, 1, 1);
    
    -- A: TRACTO ALIMENTARIO Y METABOLISMO - Antidiabéticos
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('A10BA02', 'Glucophage', 'Metformina', 'Metformina clorhidrato', 'Tableta', '850mg', v_oral_id, 1, 1);
    
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('A10AC01', 'Humulin N', 'Insulina NPH', 'Insulina humana NPH', 'Frasco', '100UI/ml', v_sc_id, 1, 1);
    
    -- A: Gastrointestinales
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('A02BC01', 'Prilosec', 'Omeprazol', 'Omeprazol magnésico', 'Cápsula', '20mg', v_oral_id, 1, 1);
    
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('A02BA02', 'Zantac', 'Ranitidina', 'Ranitidina clorhidrato', 'Tableta', '150mg', v_oral_id, 0, 1);
    
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('A03FA01', 'Reglan', 'Metoclopramida', 'Metoclopramida clorhidrato', 'Tableta', '10mg', v_oral_id, 1, 1);
    
    -- R: SISTEMA RESPIRATORIO
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('R03AC02', 'Ventolin', 'Salbutamol', 'Salbutamol sulfato', 'Inhalador', '100mcg/dosis', v_inhal_id, 1, 1);
    
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('R03BA02', 'Pulmicort', 'Budesonida', 'Budesonida', 'Inhalador', '200mcg/dosis', v_inhal_id, 1, 1);
    
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('R06AE07', 'Claritin', 'Loratadina', 'Loratadina', 'Tableta', '10mg', v_oral_id, 0, 1);
    
    -- C: Cardiovasculares - Hipolipemiantes
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('C10AA05', 'Lipitor', 'Atorvastatina', 'Atorvastatina cálcica', 'Tableta', '20mg', v_oral_id, 1, 1);
    
    -- B: SANGRE Y ÓRGANOS HEMATOPOYÉTICOS - Antitrombóticos
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('B01AC06', 'Aspirina', 'Ácido Acetilsalicílico', 'Ácido Acetilsalicílico', 'Tableta', '100mg', v_oral_id, 0, 1);
    
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('B01AC04', 'Plavix', 'Clopidogrel', 'Clopidogrel bisulfato', 'Tableta', '75mg', v_oral_id, 1, 1);
    
    -- N: SISTEMA NERVIOSO - Psicolépticos y Psicoanalépticos
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('N06AB03', 'Prozac', 'Fluoxetina', 'Fluoxetina clorhidrato', 'Cápsula', '20mg', v_oral_id, 1, 1);
    
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('N06AB06', 'Zoloft', 'Sertralina', 'Sertralina clorhidrato', 'Tableta', '50mg', v_oral_id, 1, 1);
    
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('N05BA02', 'Klonopin', 'Clonazepam', 'Clonazepam', 'Tableta', '2mg', v_oral_id, 1, 1);
    
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('N05BA01', 'Valium', 'Diazepam', 'Diazepam', 'Tableta', '10mg', v_oral_id, 1, 1);
    
    -- H: PREPARACIONES HORMONALES SISTÉMICAS
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('H03AA01', 'Synthroid', 'Levotiroxina', 'Levotiroxina sódica', 'Tableta', '100mcg', v_oral_id, 1, 1);
    
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('H02AB07', 'Deltasone', 'Prednisona', 'Prednisona', 'Tableta', '20mg', v_oral_id, 1, 1);
    
    -- D: DERMATOLÓGICOS
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('D01AC01', 'Lotrimin', 'Clotrimazol', 'Clotrimazol', 'Crema', '1%', v_top_id, 0, 1);
    
    -- S: ÓRGANOS DE LOS SENTIDOS - Oftalmológicos
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('S01ED01', 'Timoptic', 'Timolol', 'Timolol maleato', 'Gotas oftálmicas', '0.5%', v_oftal_id, 1, 1);
    
    -- B: Vitaminas
    INSERT INTO MEDICATIONS (MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, ACTIVE_INGREDIENT, PRESENTATION, CONCENTRATION, ADMINISTRATION_ROUTE_ID, REQUIRES_PRESCRIPTION, IS_ACTIVE)
    VALUES ('B03BB01', 'Folvite', 'Ácido Fólico', 'Ácido Fólico', 'Tableta', '5mg', v_oral_id, 0, 1);
    
    v_count := 35;
    DBMS_OUTPUT.PUT_LINE('Inserted ' || v_count || ' medications with WHO ATC codes');
    
    COMMIT;
END;
/

PROMPT 
PROMPT ========================================
PROMPT MEDICATIONS Data Completed!
PROMPT ========================================
PROMPT Total medications with WHO ATC codes: 35
PROMPT Compatible with HL7 FHIR R4 and OMS standards
PROMPT ========================================

-- Verify data
SELECT COUNT(*) as TOTAL_MEDICATIONS FROM MEDICATIONS;

SELECT 'Medications by ATC classification:' as INFO FROM DUAL;
SELECT SUBSTR(MEDICATION_CODE, 1, 1) as ATC_CLASS,
       CASE SUBSTR(MEDICATION_CODE, 1, 1)
           WHEN 'A' THEN 'Tracto alimentario y metabolismo'
           WHEN 'B' THEN 'Sangre y órganos hematopoyéticos'
           WHEN 'C' THEN 'Sistema cardiovascular'
           WHEN 'D' THEN 'Dermatológicos'
           WHEN 'H' THEN 'Preparaciones hormonales'
           WHEN 'J' THEN 'Antiinfecciosos'
           WHEN 'M' THEN 'Sistema musculoesquelético'
           WHEN 'N' THEN 'Sistema nervioso'
           WHEN 'R' THEN 'Sistema respiratorio'
           WHEN 'S' THEN 'Órganos de los sentidos'
       END as DESCRIPTION,
       COUNT(*) as COUNT
FROM MEDICATIONS
GROUP BY SUBSTR(MEDICATION_CODE, 1, 1)
ORDER BY 1;

SELECT 'Sample medications with ATC codes and special characters:' as INFO FROM DUAL;
SELECT MEDICATION_CODE, COMMERCIAL_NAME, GENERIC_NAME, CONCENTRATION
FROM MEDICATIONS
WHERE GENERIC_NAME LIKE '%ó%' OR GENERIC_NAME LIKE '%á%' OR GENERIC_NAME LIKE '%í%'
FETCH FIRST 5 ROWS ONLY;

PROMPT ========================================

EXIT;
