// This file is intentionally left minimal as it will be auto-generated by EF Core
// when migrations are properly scaffolded. For now, this serves as a placeholder
// to ensure the migration infrastructure is in place.

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using EPrescription.Infrastructure.Persistence;

#nullable disable

namespace EPrescription.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EPrescriptionDbContext))]
    partial class EPrescriptionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            // This snapshot will be auto-generated by EF Core
            // when the migration is properly applied
        }
    }
}
