-- Contar cuántas prescripciones tiene cada paciente
SELECT 
    PATIENT_ID,
    COUNT(*) as NUM_PRESCRIPTIONS
FROM PRESCRIPTIONS
GROUP BY PATIENT_ID
ORDER BY NUM_PRESCRIPTIONS DESC;

-- Ver los primeros 10 patient IDs únicos
SELECT DISTINCT PATIENT_ID 
FROM PRESCRIPTIONS 
ORDER BY PATIENT_ID
FETCH FIRST 10 ROWS ONLY;
