-- Check if prescription has medications
SELECT COUNT(*) as medication_count
FROM PRESCRIPTION_MEDICATIONS
WHERE "PRESCRIPTION_ID" = '6a306a43-cec9-7710-e063-020016ac555e';

-- Show the medications if they exist
SELECT "PRESCRIPTION_MEDICATION_ID", "PRESCRIPTION_ID", "MEDICATION_ID", "DOSAGE", "FREQUENCY"
FROM PRESCRIPTION_MEDICATIONS
WHERE "PRESCRIPTION_ID" = '6a306a43-cec9-7710-e063-020016ac555e';

-- Check all prescriptions with medications
SELECT DISTINCT p."ID", p."PRESCRIPTION_NUMBER", COUNT(pm."PRESCRIPTION_MEDICATION_ID") as med_count
FROM PRESCRIPTIONS p
LEFT JOIN PRESCRIPTION_MEDICATIONS pm ON p."ID" = pm."PRESCRIPTION_ID"
WHERE p."STATUS" = 'active'
GROUP BY p."ID", p."PRESCRIPTION_NUMBER"
HAVING COUNT(pm."PRESCRIPTION_MEDICATION_ID") > 0
ORDER BY p."CREATED_AT" DESC
FETCH FIRST 10 ROWS ONLY;
