-- Check all medications in PRESCRIPTION_MEDICATIONS table
SELECT 
  "PRESCRIPTION_MEDICATION_ID",
  "PRESCRIPTION_ID",
  "MEDICATION_ID",
  "DOSAGE",
  "FREQUENCY",
  "DURATION_DAYS",
  "QUANTITY",
  "CREATED_AT"
FROM PRESCRIPTION_MEDICATIONS
ORDER BY "CREATED_AT" DESC;

-- Count medications per prescription
SELECT 
  "PRESCRIPTION_ID",
  COUNT(*) as medication_count
FROM PRESCRIPTION_MEDICATIONS
GROUP BY "PRESCRIPTION_ID"
ORDER BY medication_count DESC;

-- Check if the specific prescription has medications
SELECT 
  "PRESCRIPTION_MEDICATION_ID",
  "PRESCRIPTION_ID",
  "MEDICATION_ID",
  "DOSAGE",
  "FREQUENCY"
FROM PRESCRIPTION_MEDICATIONS
WHERE "PRESCRIPTION_ID" = '6a306a43-cec9-7710-e063-020016ac555e';

-- Check all prescriptions and their medication counts
SELECT 
  p."ID",
  p."PRESCRIPTION_NUMBER",
  p."STATUS",
  COUNT(pm."PRESCRIPTION_MEDICATION_ID") as med_count
FROM PRESCRIPTIONS p
LEFT JOIN PRESCRIPTION_MEDICATIONS pm ON p."ID" = pm."PRESCRIPTION_ID"
GROUP BY p."ID", p."PRESCRIPTION_NUMBER", p."STATUS"
ORDER BY p."CREATED_AT" DESC
FETCH FIRST 20 ROWS ONLY;
