-- Verificar datos de una prescripción específica
SELECT 
    ID,
    PRESCRIPTION_NUMBER,
    PATIENT_ID,
    DOCTOR_ID,
    STATUS,
    PRESCRIPTION_DATE
FROM PRESCRIPTIONS 
WHERE PRESCRIPTION_NUMBER = 'RX-CR-2025-000029';

-- Verificar si tiene medicamentos
SELECT COUNT(*) as MEDICATION_COUNT
FROM PRESCRIPTION_MEDICATIONS 
WHERE PRESCRIPTION_ID = (
    SELECT ID FROM PRESCRIPTIONS WHERE PRESCRIPTION_NUMBER = 'RX-CR-2025-000029'
);

-- Verificar si tiene diagnósticos
SELECT COUNT(*) as DIAGNOSIS_COUNT
FROM PRESCRIPTION_DIAGNOSES 
WHERE PRESCRIPTION_ID = (
    SELECT ID FROM PRESCRIPTIONS WHERE PRESCRIPTION_NUMBER = 'RX-CR-2025-000029'
);
