SELECT COUNT(*) as total_logs FROM AUDIT_LOGS WHERE ENTITY_TYPE = 'Prescription';
SELECT * FROM (SELECT ACTION_TYPE, ENTITY_TYPE, USER_ID, USERNAME, TO_CHAR(TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS') as TS FROM AUDIT_LOGS WHERE ENTITY_TYPE = 'Prescription' ORDER BY TIMESTAMP DESC) WHERE ROWNUM <= 3;
EXIT;
