-- Verificar IDs en la tabla PRESCRIPTIONS
SELECT 
    PRESCRIPTION_ID,
    PATIENT_ID,
    DOCTOR_ID,
    PRESCRIPTION_DATE,
    STATUS
FROM PRESCRIPTIONS
ORDER BY CREATED_AT DESC
FETCH FIRST 10 ROWS ONLY;

-- Verificar IDs únicos de pacientes
SELECT DISTINCT PATIENT_ID, COUNT(*) as COUNT
FROM PRESCRIPTIONS
GROUP BY PATIENT_ID;

-- Verificar IDs únicos de doctores
SELECT DISTINCT DOCTOR_ID, COUNT(*) as COUNT
FROM PRESCRIPTIONS
GROUP BY DOCTOR_ID;

-- Ver datos de la tabla PATIENTS
SELECT 
    PATIENT_ID,
    FIRST_NAME,
    LAST_NAME,
    ID_NUMBER
FROM PATIENTS
FETCH FIRST 10 ROWS ONLY;

-- Ver datos de la tabla DOCTORS
SELECT 
    DOCTOR_ID,
    FIRST_NAME,
    LAST_NAME,
    LICENSE_NUMBER
FROM DOCTORS
FETCH FIRST 10 ROWS ONLY;
