SET PAGESIZE 0
SET FEEDBACK OFF
SET HEADING OFF
SET LINESIZE 200

SELECT 'PATIENT_ID=' || id FROM patients WHERE ROWNUM = 1;
SELECT 'DOCTOR_ID=' || id FROM doctors WHERE ROWNUM = 1;
SELECT 'MEDICAL_CENTER_ID=' || id FROM medical_centers WHERE ROWNUM = 1;
SELECT 'MEDICATION_ID=' || id FROM medications WHERE ROWNUM = 1;
SELECT 'ROUTE_ID=' || id FROM administration_routes WHERE ROWNUM = 1;

EXIT;
