SET SERVEROUTPUT ON
SET FEEDBACK ON
SET ECHO ON

PROMPT Insertando datos de prueba...

INSERT INTO ADDRESSES (COUNTRY, PROVINCE, CANTON, CITY) 
VALUES ('Ecuador', 'Pichincha', 'Quito', 'Quito');

INSERT INTO SPECIALTIES (SPECIALTY_CODE, SPECIALTY_NAME) 
VALUES ('MG', 'Medicina General');

INSERT INTO ADMINISTRATION_ROUTES (ROUTE_CODE, ROUTE_NAME) 
VALUES ('ORAL', 'Via Oral');

INSERT INTO CIE10_CATALOG (CODE, DESCRIPTION_ES, CATEGORY, CHAPTER) 
VALUES ('J00', 'Rinofaringitis aguda', 'Infecciones respiratorias', 'Enfermedades respiratorias');

INSERT INTO PHARMACIES (PHARMACY_NAME, LICENSE_NUMBER, CITY) 
VALUES ('Farmacia Test', 'TEST-001', 'Quito');

COMMIT;

PROMPT Verificando datos insertados...
SELECT 'ADDRESSES: ' || COUNT(*) FROM ADDRESSES;
SELECT 'SPECIALTIES: ' || COUNT(*) FROM SPECIALTIES;
SELECT 'ROUTES: ' || COUNT(*) FROM ADMINISTRATION_ROUTES;
SELECT 'CIE10: ' || COUNT(*) FROM CIE10_CATALOG;
SELECT 'PHARMACIES: ' || COUNT(*) FROM PHARMACIES;

EXIT;
