SET PAGESIZE 50
SET LINESIZE 120

PROMPT ========================================
PROMPT Verificando estructura de TODAS las tablas
PROMPT ========================================

PROMPT 
PROMPT === ADDRESSES ===
DESC ADDRESSES;

PROMPT 
PROMPT === SPECIALTIES ===
DESC SPECIALTIES;

PROMPT 
PROMPT === ADMINISTRATION_ROUTES ===
DESC ADMINISTRATION_ROUTES;

PROMPT 
PROMPT === CIE10_CATALOG ===
DESC CIE10_CATALOG;

PROMPT 
PROMPT === MEDICAL_CENTERS ===
DESC MEDICAL_CENTERS;

PROMPT 
PROMPT === PATIENTS ===
DESC PATIENTS;

PROMPT 
PROMPT === PATIENT_CONTACTS ===
DESC PATIENT_CONTACTS;

PROMPT 
PROMPT === PATIENT_ALLERGIES ===
DESC PATIENT_ALLERGIES;

PROMPT 
PROMPT === DOCTORS ===
DESC DOCTORS;

PROMPT 
PROMPT === MEDICATIONS ===
DESC MEDICATIONS;

PROMPT 
PROMPT === PHARMACIES ===
DESC PHARMACIES;

PROMPT 
PROMPT === INVENTORY ===
DESC INVENTORY;

PROMPT 
PROMPT === PRESCRIPTIONS ===
DESC PRESCRIPTIONS;

PROMPT 
PROMPT === PRESCRIPTION_DIAGNOSES ===
DESC PRESCRIPTION_DIAGNOSES;

PROMPT 
PROMPT === PRESCRIPTION_MEDICATIONS ===
DESC PRESCRIPTION_MEDICATIONS;

PROMPT 
PROMPT === DISPENSATIONS ===
DESC DISPENSATIONS;

PROMPT 
PROMPT === USERS ===
DESC USERS;

PROMPT 
PROMPT === ROLES ===
DESC ROLES;

PROMPT 
PROMPT === AUDIT_LOGS ===
DESC AUDIT_LOGS;

EXIT;
