-- ============================================================================
-- Fase 0: Crear Tablas de Talonarios (Prescription Pads)
-- ============================================================================
-- Fecha: 2025-12-04
-- Descripción: Crear infraestructura de BD para gestión de talonarios
-- ============================================================================

-- 1. Crear tabla PRESCRIPTION_PAD_TYPES (Catálogo de tipos de talonarios)
-- ============================================================================
CREATE TABLE PRESCRIPTION_PAD_TYPES (
    PAD_TYPE_ID RAW(16) PRIMARY KEY,
    PAD_TYPE_NAME VARCHAR2(100) NOT NULL,
    PAD_TYPE_CODE VARCHAR2(20) NOT NULL UNIQUE,
    DEFAULT_QUANTITY NUMBER(5,0) DEFAULT 50,
    DESCRIPTION VARCHAR2(500),
    IS_ACTIVE NUMBER(1,0) DEFAULT 1,
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);

-- Crear índice en PAD_TYPE_CODE
CREATE UNIQUE INDEX UK_PAD_TYPE_CODE ON PRESCRIPTION_PAD_TYPES(PAD_TYPE_CODE);

-- Insertar tipos de talonarios
INSERT INTO PRESCRIPTION_PAD_TYPES (PAD_TYPE_ID, PAD_TYPE_NAME, PAD_TYPE_CODE, DEFAULT_QUANTITY, DESCRIPTION, IS_ACTIVE)
VALUES (SYS_GUID(), 'Libre/Normal', 'LIBRE', 50, 'Talonario para medicamentos de venta libre', 1);

INSERT INTO PRESCRIPTION_PAD_TYPES (PAD_TYPE_ID, PAD_TYPE_NAME, PAD_TYPE_CODE, DEFAULT_QUANTITY, DESCRIPTION, IS_ACTIVE)
VALUES (SYS_GUID(), 'Antimicrobianos', 'ANTIMICRO', 50, 'Talonario para medicamentos antimicrobianos', 1);

INSERT INTO PRESCRIPTION_PAD_TYPES (PAD_TYPE_ID, PAD_TYPE_NAME, PAD_TYPE_CODE, DEFAULT_QUANTITY, DESCRIPTION, IS_ACTIVE)
VALUES (SYS_GUID(), 'Psicotrópicos', 'PSICO', 50, 'Talonario para medicamentos psicotrópicos', 1);

INSERT INTO PRESCRIPTION_PAD_TYPES (PAD_TYPE_ID, PAD_TYPE_NAME, PAD_TYPE_CODE, DEFAULT_QUANTITY, DESCRIPTION, IS_ACTIVE)
VALUES (SYS_GUID(), 'Estupefacientes', 'ESTUP', 50, 'Talonario para medicamentos estupefacientes', 1);

COMMIT;

-- 2. Crear tabla PRESCRIPTION_PADS (Talonarios por doctor)
-- ============================================================================
CREATE TABLE PRESCRIPTION_PADS (
    PRESCRIPTION_PAD_ID RAW(16) PRIMARY KEY,
    DOCTOR_ID RAW(16) NOT NULL,
    PAD_TYPE_ID RAW(16) NOT NULL,
    PAD_NUMBER VARCHAR2(50) NOT NULL,
    AVAILABLE_COUNT NUMBER(5,0) NOT NULL,
    TOTAL_COUNT NUMBER(5,0) NOT NULL,
    EXPIRATION_DATE DATE NOT NULL,
    IS_ACTIVE NUMBER(1,0) DEFAULT 1,
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PAD_DOCTOR FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTORS(DOCTOR_ID),
    CONSTRAINT FK_PAD_TYPE FOREIGN KEY (PAD_TYPE_ID) REFERENCES PRESCRIPTION_PAD_TYPES(PAD_TYPE_ID),
    CONSTRAINT UK_PAD_DOCTOR_TYPE_NUMBER UNIQUE (DOCTOR_ID, PAD_TYPE_ID, PAD_NUMBER),
    CONSTRAINT CHK_PAD_COUNT CHECK (AVAILABLE_COUNT <= TOTAL_COUNT)
);

-- Crear índices
CREATE INDEX IDX_PAD_DOCTOR ON PRESCRIPTION_PADS(DOCTOR_ID);
CREATE INDEX IDX_PAD_TYPE ON PRESCRIPTION_PADS(PAD_TYPE_ID);
CREATE INDEX IDX_PAD_EXPIRATION ON PRESCRIPTION_PADS(EXPIRATION_DATE);

-- 3. Crear tabla PRESCRIPTION_SLIPS (Boletas individuales)
-- ============================================================================
CREATE TABLE PRESCRIPTION_SLIPS (
    SLIP_ID RAW(16) PRIMARY KEY,
    PRESCRIPTION_PAD_ID RAW(16) NOT NULL,
    SLIP_NUMBER NUMBER(5,0) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'available',
    USED_BY_PRESCRIPTION_ID RAW(16),
    USED_AT TIMESTAMP(6),
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SLIP_PAD FOREIGN KEY (PRESCRIPTION_PAD_ID) REFERENCES PRESCRIPTION_PADS(PRESCRIPTION_PAD_ID),
    CONSTRAINT FK_SLIP_PRESCRIPTION FOREIGN KEY (USED_BY_PRESCRIPTION_ID) REFERENCES PRESCRIPTIONS(PRESCRIPTION_ID),
    CONSTRAINT UK_SLIP_PAD_NUMBER UNIQUE (PRESCRIPTION_PAD_ID, SLIP_NUMBER)
);

-- Crear índices
CREATE INDEX IDX_SLIP_PAD ON PRESCRIPTION_SLIPS(PRESCRIPTION_PAD_ID);
CREATE INDEX IDX_SLIP_STATUS ON PRESCRIPTION_SLIPS(STATUS);
CREATE INDEX IDX_SLIP_PRESCRIPTION ON PRESCRIPTION_SLIPS(USED_BY_PRESCRIPTION_ID);

-- 4. Actualizar tabla MEDICATIONS (Agregar PAD_TYPE_ID)
-- ============================================================================
ALTER TABLE MEDICATIONS ADD (
    PAD_TYPE_ID RAW(16),
    CONSTRAINT FK_MED_PAD_TYPE FOREIGN KEY (PAD_TYPE_ID) REFERENCES PRESCRIPTION_PAD_TYPES(PAD_TYPE_ID)
);

-- Crear índice
CREATE INDEX IDX_MED_PAD_TYPE ON MEDICATIONS(PAD_TYPE_ID);

-- 5. Validación de tablas creadas
-- ============================================================================
-- Ejecutar después de crear las tablas para validar:
-- SELECT TABLE_NAME FROM USER_TABLES 
-- WHERE TABLE_NAME IN ('PRESCRIPTION_PAD_TYPES', 'PRESCRIPTION_PADS', 'PRESCRIPTION_SLIPS');

-- SELECT * FROM PRESCRIPTION_PAD_TYPES;

COMMIT;

-- ============================================================================
-- FIN: Fase 0 - Crear Tablas de Talonarios
-- ============================================================================
