-- =====================================================
-- Script: fix-prescription-schema.sql
-- Descripción: Agregar columnas faltantes para Task 11
-- Autor: Kiro AI
-- Fecha: 2025-11-19
-- =====================================================

CONNECT eprescription_user/EprescriptionPass123!@localhost:1521/XEPDB1

-- Agregar UPDATED_AT a PRESCRIPTION_MEDICATIONS
ALTER TABLE PRESCRIPTION_MEDICATIONS ADD UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Agregar UPDATED_AT a PRESCRIPTION_DIAGNOSES  
ALTER TABLE PRESCRIPTION_DIAGNOSES ADD UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Actualizar valores existentes
UPDATE PRESCRIPTION_MEDICATIONS SET UPDATED_AT = CREATED_AT WHERE UPDATED_AT IS NULL;
UPDATE PRESCRIPTION_DIAGNOSES SET UPDATED_AT = CREATED_AT WHERE UPDATED_AT IS NULL;

COMMIT;

-- Verificar cambios
SELECT 'PRESCRIPTION_MEDICATIONS columns:' AS info FROM DUAL;
DESC PRESCRIPTION_MEDICATIONS;

SELECT 'PRESCRIPTION_DIAGNOSES columns:' AS info FROM DUAL;
DESC PRESCRIPTION_DIAGNOSES;

EXIT;
