-- Fix UTF-8 encoding for SPECIALTIES
ALTER SESSION SET NLS_LANGUAGE='SPANISH';
ALTER SESSION SET NLS_TERRITORY='COSTA RICA';

-- Delete in correct order
DELETE FROM DOCTOR_MEDICAL_CENTERS;
DELETE FROM DOCTORS;
DELETE FROM ADMINISTRATION_ROUTES;
DELETE FROM SPECIALTIES;

-- Re-insert with correct UTF-8
INSERT INTO SPECIALTIES (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES ('MG', 'Medicina General', 'Atención médica general y preventiva');
INSERT INTO SPECIALTIES (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES ('CARD', 'Cardiología', 'Especialidad médica del corazón');
INSERT INTO SPECIALTIES (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES ('DERM', 'Dermatología', 'Especialidad de la piel');
INSERT INTO SPECIALTIES (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES ('ENDO', 'Endocrinología', 'Especialidad de hormonas');
INSERT INTO SPECIALTIES (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES ('GASTRO', 'Gastroenterología', 'Especialidad digestiva');
INSERT INTO SPECIALTIES (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES ('GINE', 'Ginecología y Obstetricia', 'Especialidad reproductiva femenina');
INSERT INTO SPECIALTIES (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES ('HEMA', 'Hematología', 'Especialidad de la sangre');
INSERT INTO SPECIALTIES (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES ('INFEC', 'Infectología', 'Especialidad infecciosa');
INSERT INTO SPECIALTIES (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES ('MI', 'Medicina Interna', 'Atención integral del adulto');
INSERT INTO SPECIALTIES (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES ('NEFRO', 'Nefrología', 'Especialidad del riñón');
INSERT INTO SPECIALTIES (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES ('NEUMO', 'Neumología', 'Especialidad respiratoria');
INSERT INTO SPECIALTIES (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES ('NEURO', 'Neurología', 'Especialidad del sistema nervioso');
INSERT INTO SPECIALTIES (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES ('OFTAL', 'Oftalmología', 'Especialidad de los ojos');
INSERT INTO SPECIALTIES (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES ('ONCO', 'Oncología', 'Especialidad del cáncer');
INSERT INTO SPECIALTIES (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES ('ORTO', 'Ortopedia y Traumatología', 'Especialidad musculoesquelética');
INSERT INTO SPECIALTIES (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES ('ORL', 'Otorrinolaringología', 'Especialidad de oído, nariz y garganta');
INSERT INTO SPECIALTIES (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES ('PED', 'Pediatría', 'Especialidad del niño');
INSERT INTO SPECIALTIES (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES ('PSIQ', 'Psiquiatría', 'Especialidad de trastornos mentales');
INSERT INTO SPECIALTIES (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES ('REUMA', 'Reumatología', 'Especialidad del aparato locomotor');
INSERT INTO SPECIALTIES (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES ('URO', 'Urología', 'Especialidad del aparato urinario');
INSERT INTO SPECIALTIES (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES ('CG', 'Cirugía General', 'Especialidad quirúrgica');
INSERT INTO SPECIALTIES (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES ('ANES', 'Anestesiología', 'Especialidad de anestesia');
INSERT INTO SPECIALTIES (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES ('RAD', 'Radiología', 'Especialidad de imágenes');
INSERT INTO SPECIALTIES (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES ('EMERG', 'Medicina de Emergencia', 'Especialidad de urgencias');
INSERT INTO SPECIALTIES (SPECIALTY_CODE, SPECIALTY_NAME, DESCRIPTION) VALUES ('GERI', 'Geriatría', 'Especialidad de personas mayores');

-- Re-insert routes
INSERT INTO ADMINISTRATION_ROUTES (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES ('ORAL', 'Oral', 'Vía oral');
INSERT INTO ADMINISTRATION_ROUTES (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES ('SUBL', 'Sublingual', 'Debajo de la lengua');
INSERT INTO ADMINISTRATION_ROUTES (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES ('IV', 'Intravenosa', 'Directa en vena');
INSERT INTO ADMINISTRATION_ROUTES (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES ('IM', 'Intramuscular', 'En músculo');
INSERT INTO ADMINISTRATION_ROUTES (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES ('SC', 'Subcutánea', 'Bajo la piel');
INSERT INTO ADMINISTRATION_ROUTES (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES ('TOP', 'Tópica', 'Sobre la piel');
INSERT INTO ADMINISTRATION_ROUTES (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES ('TRANS', 'Transdérmica', 'A través de la piel');
INSERT INTO ADMINISTRATION_ROUTES (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES ('INHAL', 'Inhalatoria', 'Por inhalación');
INSERT INTO ADMINISTRATION_ROUTES (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES ('NASAL', 'Nasal', 'Vía nasal');
INSERT INTO ADMINISTRATION_ROUTES (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES ('OFTAL', 'Oftálmica', 'En los ojos');
INSERT INTO ADMINISTRATION_ROUTES (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES ('OTIC', 'Ótica', 'En los oídos');
INSERT INTO ADMINISTRATION_ROUTES (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES ('RECT', 'Rectal', 'Vía rectal');
INSERT INTO ADMINISTRATION_ROUTES (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES ('VAG', 'Vaginal', 'Vía vaginal');
INSERT INTO ADMINISTRATION_ROUTES (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES ('ID', 'Intradérmica', 'En la dermis');
INSERT INTO ADMINISTRATION_ROUTES (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES ('IP', 'Intraperitoneal', 'En cavidad peritoneal');
INSERT INTO ADMINISTRATION_ROUTES (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES ('IT', 'Intratecal', 'En espacio subaracnoideo');
INSERT INTO ADMINISTRATION_ROUTES (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES ('EPID', 'Epidural', 'En espacio epidural');
INSERT INTO ADMINISTRATION_ROUTES (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES ('IA', 'Intraarticular', 'Dentro de articulación');
INSERT INTO ADMINISTRATION_ROUTES (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES ('BUCAL', 'Bucal', 'Entre mejilla y encía');
INSERT INTO ADMINISTRATION_ROUTES (ROUTE_CODE, ROUTE_NAME, DESCRIPTION) VALUES ('PARENT', 'Parenteral', 'Evita tracto gastrointestinal');

COMMIT;

SELECT 'Fixed!' as status, SPECIALTY_CODE, SPECIALTY_NAME FROM SPECIALTIES WHERE ROWNUM <= 5 ORDER BY SPECIALTY_CODE;
EXIT;
